from rest_framework import serializers
from .models import CV, HeaderLink, Section, Entry, Bullet


class BulletSerializer(serializers.ModelSerializer):
    class Meta:
        model = Bullet # model is always defined in Meta, tell me WHICH model to read from
        fields = ["id", "text", "order"] # fields is always defined in Meta,tell me WHICH fields to include


class EntrySerializer(serializers.ModelSerializer):
    # nested child serializer — 'bullets' matches related_name in models.py
    bullets = BulletSerializer(many=True)

    # fields defined explicitly above Meta because they need renaming (camelCase → snake_case)
    # left side = JSON key React sees, source = actual Django model field name in models.py
    jobTitle = serializers.CharField(source="job_title", allow_blank=True, required=False)
    companyURL = serializers.URLField(
        source="company_url", allow_blank=True, required=False
        # URLField (type from models.py like CharField but with built in enforcment) needs required=False — strict by default, rejects missing fields
    )
    linkLabel = serializers.CharField(source="link_label", allow_blank=True, required=False)
    startDate = serializers.CharField(source="start_date", allow_blank=True, required=False)
    endDate = serializers.CharField(source="end_date", allow_blank=True, required=False)
    institutionURL = serializers.URLField(
        source="institution_url", allow_blank=True, required=False
    )
    linkUrl = serializers.URLField(source="link_url", allow_blank=True, required=False)

    class Meta:
        model = Entry
        fields = [
            # complete output manifest — everything that appears in the JSON
            # auto from model (same name in Django and React, no explicit definition needed)
            "id",           # auto-generated by Django on every model
            "order",
            "company",
            "degree",
            "institution",
            "subheading",
            "location",
            "text",
            # explicitly defined above Meta (renamed camelCase fields)
            "jobTitle",
            "companyURL",
            "institutionURL",
            "linkLabel",
            "linkUrl",
            "startDate",
            "endDate",
            # nested child serializer defined above Meta
            "bullets",
        ]


class SectionSerializer(serializers.ModelSerializer):
    entries = EntrySerializer(many=True)

    class Meta:
        model = Section
        fields = ["id", "title", "type", "order", "entries"]


class HeaderLinkSerializer(serializers.ModelSerializer):
    class Meta:
        model = HeaderLink
        fields = ["id", "label", "url", "order"]


class CVSerializer(serializers.ModelSerializer):
    links = HeaderLinkSerializer(many=True)
    sections = SectionSerializer(many=True)

    visaStatus = serializers.CharField(source="visa_status", allow_blank=True)
    fontSize = serializers.CharField(source="font_size")
    accentColor = serializers.CharField(source="accent_color")

    class Meta:
        model = CV
        fields = [
            "id",
            "name",
            "title",
            "location",
            "phone",
            "email",
            "address",
            "visaStatus",
            "font",
            "fontSize",
            "margins",
            "accentColor",
            "links",
            "sections",
        ]
        
        
# 1. Pop links and sections out → set aside for later
#2. Create CV (now validated_data only has flat CV fields) → get CV id back
#3. Deal with the two things you popped:
#   - create links (using CV id to set FK)
#   - create sections (using CV id to set FK)
#        - but first pop entries out of each section
#- create section → get section id back
#        - create entries (using section id to set FK)
#              - but first pop bullets out of each entry
#              - create entry → get entry id back
#              - create bullets (using entry id to set FK)

    def create(self, validated_data): # validated_data is a dictionary containing the cleaned, validated data from the incoming json request, after DRF has checked it all passes validation. i.e json converted to python for us to manipulate
        # pull nested lists out of validated_data before creating CV
        # must do this first — CV model has no 'links' or 'sections' fields
        # if we don't pop them, CV.objects.create(**validated_data) would crash
        links_data = validated_data.pop("links", [])      # [] = default if key missing
        sections_data = validated_data.pop("sections", [])

        # create the CV row first — we need its id before creating children
        cv = CV.objects.create(**validated_data) # star star is python dictionary unpacking operator of the parameter passed in at the top. spreads out as keyword arugments, without it id have to do name=validated_data['name], title=validated_data['title] etc
        
        #cv is now a python objecting representing that DB row, i.e a cv row, which has cv.id, cv.name, cv.title etc

        # create links — enumerate gives us index (order) + value (link_data) together
        # order becomes the DB ordering field so links come back in the right sequence
        for order, link_data in enumerate(links_data): # arugment is from the top where we defined it
            HeaderLink.objects.create(cv=cv, order=order, **link_data)

        # create sections — same pattern but nested deeper
        for s_order, section_data in enumerate(sections_data): # arugment is from the top where we defined it
            # pop entries out before creating section — same reason as above
            # Section model has no 'entries' field, it's a related model
            entries_data = section_data.pop("entries", [])

            # create section row — cv=cv sets the FK back to the parent CV
            section = Section.objects.create(cv=cv, order=s_order, **section_data)

            # create entries for this section
            for e_order, entry_data in enumerate(entries_data):
                # pop bullets out before creating entry — same pattern again
                bullets_data = entry_data.pop("bullets", [])

                # create entry row — section=section sets FK back to parent section
                entry = Entry.objects.create(
                    section=section, order=e_order, **entry_data
                )

                # create bullets for this entry — bottom of the tree, no children to pop
                for b_order, bullet_data in enumerate(bullets_data):
                    Bullet.objects.create(entry=entry, order=b_order, **bullet_data)

        # return the created CV instance — DRF expects this
        return cv

    def update(self, instance, validated_data): # instance is the existing CV OBJECT fetched from the DB (use . to access attributes on it), which now needs updating, its a full django model instance with all its current field values, i.e instance. id  (1) , instance.name ('Sherlock Holmes) etc. We can chain as deep as the tree goes using related names, i.e instance.sections.first().entries.first().bullets.all() , that's why we use settattr below because we're setting attributes on an object (not a dictionary, where as validated_data is a dictionary, thats why we use .items(), .pop(0 etc on it))
        # same pop pattern — pull nested data out before touching CV fields
        links_data = validated_data.pop("links", [])
        sections_data = validated_data.pop("sections", [])

        # update CV's own flat fields (name, title, email etc)
        # setattr(instance, 'name', 'Sherlock') = instance.name = 'Sherlock'
        # loop does this for every remaining field in validated_data at once
        for attr, value in validated_data.items():
            setattr(instance, attr, value) # built in function, sets an attribute on an object dynamically, equivalent to object.attr = value
        instance.save()  # write the updated CV fields to DB

        # delete-and-recreate strategy for nested data
        # simpler than figuring out what changed — just wipe and rebuild
        # instance.links uses related_name='links' to find all HeaderLink rows for this CV
        instance.links.all().delete()
        for order, link_data in enumerate(links_data):
            HeaderLink.objects.create(cv=instance, order=order, **link_data) # delete all links and then just rebuild each link from link_data which comes from links_data which comes from validated_data. Cv=instance means this is the FK for this (i.e parent)

        # deleting sections cascades automatically to entries and bullets
        # because on_delete=models.CASCADE on each FK
        # so one delete wipes the whole tree below sections
        instance.sections.all().delete()
        for s_order, section_data in enumerate(sections_data):
            entries_data = section_data.pop("entries", [])
            section = Section.objects.create(cv=instance, order=s_order, **section_data) #cv the parent of this section, fetched from the DB , 

            for e_order, entry_data in enumerate(entries_data):
                bullets_data = entry_data.pop("bullets", [])
                entry = Entry.objects.create(
                    section=section, order=e_order, **entry_data #section is the object we just created in the level above, the parent of this entry
                )

                for b_order, bullet_data in enumerate(bullets_data): # could have used order instead of s_order, b_order, e_order because each has its own scope but did different for readability and debugging 
                    Bullet.objects.create(entry=entry, order=b_order, **bullet_data) #entry is the object we just created in the level above, the parent of this bullet

        # return the updated instance — DRF expects this
        return instance