# Generated by Django 6.0.3 on 2026-04-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="headerlink",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="headerlink",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bullet",
            name="text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="cv",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="cv",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="cv",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="cv",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="cv",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="headerlink",
            name="label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="headerlink",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
